import { NextResponse } from 'next/server'

const SUPPORTED_LOCALES = ['zh-CN', 'ja-JP']
const COOKIE_NAME = 'NEXT_LOCALE'
const COOKIE_MAX_AGE = 365 * 24 * 60 * 60 // 1 year

/**
 * Locale middleware — sticky locale via functional cookie.
 *
 * 1. /zh-CN/* → ensure cookie is set, serve the page
 * 2. English path + zh-CN cookie → redirect to /zh-CN/path
 * 3. English path, no cookie → serve normally
 *
 * Every English page has a /zh-CN/ proxy (generated by scripts/generate-locale-pages.mjs),
 * so redirects always land on valid pages.
 *
 * The NEXT_LOCALE cookie is a functional/strictly-necessary cookie (GDPR exempt)
 * — it only stores the user's explicit language preference.
 */
export function middleware(request) {
  const { pathname } = request.nextUrl

  // Skip static files, API, _next
  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname.includes('.')
  ) {
    return NextResponse.next()
  }

  // Check if this is already a locale path
  const localeMatch = SUPPORTED_LOCALES.find((l) =>
    pathname.startsWith(`/${l}/`) || pathname === `/${l}`
  )

  if (localeMatch) {
    // On a locale path — ensure cookie is set
    const response = NextResponse.next()
    response.cookies.set(COOKIE_NAME, localeMatch, {
      path: '/',
      maxAge: COOKIE_MAX_AGE,
      sameSite: 'lax',
    })
    return response
  }

  // English path — check for locale cookie
  const preferredLocale = request.cookies.get(COOKIE_NAME)?.value

  if (preferredLocale && SUPPORTED_LOCALES.includes(preferredLocale)) {
    // Redirect to locale version
    const url = request.nextUrl.clone()
    url.pathname = `/${preferredLocale}${pathname}`
    return NextResponse.redirect(url)
  }

  return NextResponse.next()
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico|.*\\..*).*)',],
}
